version: '3.4'
services:
  redis:
    image: "redis:7-alpine"
    ports:
      - 6379
    volumes:
      - ./tmp/redis_data:/var/lib/redis/data

  db:
    build:
      context: ./db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5433:5432
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data

  app:
    build: ./server
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - db
      - redis
